model:
  MODEL: LinearRegression
  input_node_dim: 5    # [x,y,0,0,0] (x,y) coord + one-hot encoding
  output_node_dim: 2
dataset:
  TYPE: nba # nba-0021500225
  dataset_path: ./dataset/nba-dataset-20partial.json
  playerid_path: ./dataset/active_playerid_dict.json
  num_checked_seqs: 200
  tr_ratio: 0.7 
  val_ratio: 0.1
  te_ratio: 0.2
  missing_rate: 0.2
  num_nodes: 11    # players+ball
  num_edge_types: 4
optimizer:
  initial_lr: 0.002
  weight_decay: 0.0005
  reducer: SUM
train:
  batch_size: 8
  num_epochs: 1
  input_seq_length: 7   # number of processing steps
  val_check_step: 1
  filled_rgn: False
test:
  threshold: 0.001
  num_refill_try: 100
seed: 42